services:
 dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
     - "./docker/dynamodb-init:/docker-entrypoint-initdb.d"
   working_dir: /home/dynamodblocal
   environment:
     - AWS_ACCESS_KEY_ID=dummy
     - AWS_SECRET_ACCESS_KEY=dummy
     - AWS_REGION=localhost